# Generated by Django 4.2.1 on 2023-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(blank=True, max_length=60, null=True)),
                ('review_comment', models.TextField(blank=True, max_length=600, null=True)),
                ('review_review', models.TextField(blank=True, max_length=600, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
