# Generated by Django 4.2.1 on 2023-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=70, null=True)),
                ('blog_date', models.DateField(blank=True, null=True)),
                ('blog_text', models.TextField(blank=True, max_length=100, null=True)),
                ('blog_img', models.ImageField(upload_to='blog/')),
            ],
        ),
    ]
