# Generated by Django 4.2.1 on 2023-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0004_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(blank=True, max_length=70, null=True)),
                ('blog_date', models.DateField(blank=True, null=True)),
                ('blog_text', models.TextField(blank=True, max_length=100, null=True)),
                ('blog_img', models.ImageField(upload_to='blog/')),
            ],
        ),
    ]
