# Generated by Django 4.2.1 on 2023-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacioni', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullblog',
            fields=[
                ('fullblog_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullblog_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('fullblog_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('fullblog_img', models.ImageField(upload_to='blog/')),
                ('fullblog_date', models.CharField(blank=True, max_length=50, null=True)),
                ('fullblog_img2', models.ImageField(upload_to='blog/')),
                ('fullblog_text2', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
